-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('ASSIGNED', 'DEADLINE_APPROACHING', 'OVERDUE', 'BLOCKED', 'DELAY_CAUSED', 'RETURNED', 'REVIEW_REQUESTED', 'LATE_START', 'LATE_START_CRITICAL', 'SHARE_ACTIVITY', 'MENTION', 'URGENT_TASK', 'SYSTEM') NOT NULL;

